# Generated by Django 2.2.5 on 2019-12-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20191214_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('-created',)},
        ),
    ]
