# Generated by Django 2.2.5 on 2019-11-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20191122_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
