# Generated by Django 2.2.5 on 2019-11-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='state',
        ),
    ]
