# Generated by Django 2.2.5 on 2019-12-14 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_menu_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='businesses.Business'),
        ),
    ]
